name: Ligaofei
favicon: null
layout_spectrum: 0.7825251731555909
typography_spectrum: 0.8815525795798749
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4900305741466582
  lightness: 0.3166878775227815
  saturation: 0.8915959694422781
  rhythmicContrast: 0.38817436597310007
purpose: []
